#!/usr/bin/env bash
set -e

if [ -d /var/www/yii2site/migrations ]; then
	# Allow image to execute custom migrations before main migrations.
	if [ -f /var/www/yii2site/docker/beforemigrate ]; then
		/var/www/yii2site/docker/beforemigrate
	fi
	
	# Run migrations.
	/var/www/yii2site/yii migrate --interactive=0
	
	# Allow image to execute custom migrations after main migrations.
	if [ -f /var/www/yii2site/docker/aftermigrate ]; then
		/var/www/yii2site/docker/aftermigrate
	fi
fi

# Modify folder permissions.
chown www-data:www-data runtime
chown www-data:www-data web/assets

# Allow image to execute custom arbitrary commands before start.
if [ -f /var/www/yii2site/docker/beforestart ]; then
	/var/www/yii2site/docker/beforestart
fi

# Apache gets grumpy about PID files pre-existing.
rm -f /var/run/apache2/apache2.pid

# Start!
exec /usr/sbin/apache2ctl -D FOREGROUND